// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/solders/[solder].ts";
import * as $2 from "./routes/api/solders/index.ts";
import * as $3 from "./routes/api/stone/muffins.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/DMBTimer.tsx";
import * as $$1 from "./islands/Search.tsx";
import * as $$2 from "./islands/Solder.tsx";
import * as $$3 from "./islands/ToggleDarkMode.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/solders/[solder].ts": $1,
    "./routes/api/solders/index.ts": $2,
    "./routes/api/stone/muffins.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/DMBTimer.tsx": $$0,
    "./islands/Search.tsx": $$1,
    "./islands/Solder.tsx": $$2,
    "./islands/ToggleDarkMode.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
